// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwuYC9TxZA_2up-937idMoPzmRZ5eWulo',
    appId: '1:663316341435:web:0833025c8547798ad6ff9e',
    messagingSenderId: '663316341435',
    projectId: 'stikahub',
    authDomain: 'stikahub.firebaseapp.com',
    storageBucket: 'stikahub.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW_tWxIEvIuuv5QkqLo_inI8yw1EiSOfY',
    appId: '1:663316341435:android:c92dd12f97d70a21d6ff9e',
    messagingSenderId: '663316341435',
    projectId: 'stikahub',
    storageBucket: 'stikahub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7b7XAcIb9-YVWZbELEidjQbvjs-VEtng',
    appId: '1:663316341435:ios:50273d532ac1fac6d6ff9e',
    messagingSenderId: '663316341435',
    projectId: 'stikahub',
    storageBucket: 'stikahub.firebasestorage.app',
    iosBundleId: 'com.example.stikahub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7b7XAcIb9-YVWZbELEidjQbvjs-VEtng',
    appId: '1:663316341435:ios:50273d532ac1fac6d6ff9e',
    messagingSenderId: '663316341435',
    projectId: 'stikahub',
    storageBucket: 'stikahub.firebasestorage.app',
    iosBundleId: 'com.example.stikahub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwuYC9TxZA_2up-937idMoPzmRZ5eWulo',
    appId: '1:663316341435:web:067b9219f1721cefd6ff9e',
    messagingSenderId: '663316341435',
    projectId: 'stikahub',
    authDomain: 'stikahub.firebaseapp.com',
    storageBucket: 'stikahub.firebasestorage.app',
  );
}
